-- Phase 6G: the outcome of publishing an APPROVED workout draft, kept apart from the draft's own status (which only
-- says what the athlete approved). Only successful outcomes are stored; a failed publish leaves no row, so the
-- approved draft can simply be published again.
--
--   PUBLISHED         a workout was written to (or already matched on) Intervals.icu; the IntervalsPublishResult is
--                     recorded as-is (CREATED / UPDATED / NO_CHANGE, remote event id, verified).
--   SKIPPED_REST_DAY  the approved draft is a REST day: nothing was sent anywhere, by design, and nothing ever will be.
--
-- uk_workout_draft_publication_draft is the last line of defence against a draft being published twice; the
-- check constraint keeps a REST outcome from ever carrying remote data and a PUBLISHED outcome from lacking it.
CREATE TABLE workout_draft_publication (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id             BIGINT                   NOT NULL,
    approval_id          BIGINT                   NOT NULL,
    outcome              VARCHAR(32)              NOT NULL,
    intervals_operation  VARCHAR(32),
    remote_event_id      VARCHAR(128),
    verified             BOOLEAN,
    published_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_workout_draft_publication_draft FOREIGN KEY (draft_id) REFERENCES workout_draft (id),
    CONSTRAINT fk_workout_draft_publication_approval FOREIGN KEY (approval_id) REFERENCES workout_draft_approval (id),
    CONSTRAINT uk_workout_draft_publication_draft UNIQUE (draft_id),
    CONSTRAINT ck_workout_draft_publication_shape CHECK (
        (outcome = 'SKIPPED_REST_DAY' AND intervals_operation IS NULL AND remote_event_id IS NULL AND verified IS NULL)
        OR (outcome = 'PUBLISHED' AND intervals_operation IN ('CREATED', 'UPDATED', 'NO_CHANGE')
            AND remote_event_id IS NOT NULL AND verified IS NOT NULL)
    )
);
