-- Phase 6H-1A: raw-first storage for the per-activity DETAIL payloads (detail, splits, HR / power time in
-- zones, sample stream). The activity-list item keeps living in activity_raw (V3) exactly as before; this
-- table does not replace or duplicate it.
--
-- One row per external activity and payload type: a re-fetch replaces payload + fetched_at (same
-- semantics as activity_raw). Rows are keyed by the source's own activity id, not by activity.id, so a
-- payload can be stored before (or without) any normalisation; a mapper failure never rolls it back.
--
-- ${json_type}: JSONB on PostgreSQL, JSON on H2 (tests).
CREATE TABLE activity_raw_payload (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id            BIGINT                   NOT NULL,
    external_source       VARCHAR(32)              NOT NULL,
    external_activity_id  VARCHAR(100)             NOT NULL,
    payload_type          VARCHAR(48)              NOT NULL,
    payload               ${json_type}             NOT NULL,
    fetched_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_raw_payload_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_activity_raw_payload UNIQUE (external_source, external_activity_id, payload_type)
);
