-- Phase 6H-1A: provider-neutral normalised detail of one activity. No Garmin field name appears here;
-- the Garmin mappers translate. Every metric is nullable: a value the source did not report stays NULL and
-- is never estimated, interpolated or defaulted. Values are stored as reported (DOUBLE PRECISION, no
-- rounding); column suffixes name a unit only where the unit is confirmed (seconds, metres, bpm, steps/min).
--
-- Re-collection replaces an activity's rows (laps / zones of one type / samples are deleted and re-inserted
-- in one transaction); the unique keys below make a duplicate impossible even if that were bypassed.

-- 1:1 with activity.
CREATE TABLE activity_detail (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id                     BIGINT                   NOT NULL,
    source_payload_type             VARCHAR(48)              NOT NULL,
    duration_seconds                DOUBLE PRECISION,
    elapsed_duration_seconds        DOUBLE PRECISION,
    moving_duration_seconds         DOUBLE PRECISION,
    distance_meters                 DOUBLE PRECISION,
    average_speed                   DOUBLE PRECISION,
    max_speed                       DOUBLE PRECISION,
    average_heart_rate_bpm          DOUBLE PRECISION,
    max_heart_rate_bpm              DOUBLE PRECISION,
    average_running_cadence_spm     DOUBLE PRECISION,
    max_running_cadence_spm         DOUBLE PRECISION,
    elevation_gain                  DOUBLE PRECISION,
    elevation_loss                  DOUBLE PRECISION,
    calories                        DOUBLE PRECISION,
    average_power                   DOUBLE PRECISION,
    max_power                       DOUBLE PRECISION,
    normalized_power                DOUBLE PRECISION,
    aerobic_training_effect         DOUBLE PRECISION,
    anaerobic_training_effect       DOUBLE PRECISION,
    training_load                   DOUBLE PRECISION,
    training_effect_label           VARCHAR(64),
    created_at                      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_detail_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_detail_activity UNIQUE (activity_id)
);

-- 1:N laps / splits, in the source's order.
CREATE TABLE activity_lap (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id                BIGINT                   NOT NULL,
    lap_index                  INTEGER                  NOT NULL,
    start_time                 TIMESTAMP WITH TIME ZONE,
    duration_seconds           DOUBLE PRECISION,
    elapsed_duration_seconds   DOUBLE PRECISION,
    moving_duration_seconds    DOUBLE PRECISION,
    distance_meters            DOUBLE PRECISION,
    average_speed              DOUBLE PRECISION,
    max_speed                  DOUBLE PRECISION,
    average_heart_rate_bpm     DOUBLE PRECISION,
    max_heart_rate_bpm         DOUBLE PRECISION,
    average_cadence            DOUBLE PRECISION,
    max_cadence                DOUBLE PRECISION,
    average_power              DOUBLE PRECISION,
    max_power                  DOUBLE PRECISION,
    elevation_gain             DOUBLE PRECISION,
    elevation_loss             DOUBLE PRECISION,
    calories                   DOUBLE PRECISION,
    extra_metrics              ${json_type},
    CONSTRAINT fk_activity_lap_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_lap UNIQUE (activity_id, lap_index),
    CONSTRAINT ck_activity_lap_index CHECK (lap_index >= 0)
);

-- 1:N time in zone (heart rate / power).
CREATE TABLE activity_zone (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id       BIGINT           NOT NULL,
    zone_type         VARCHAR(16)      NOT NULL,
    zone_number       INTEGER          NOT NULL,
    min_value         DOUBLE PRECISION,
    max_value         DOUBLE PRECISION,
    duration_seconds  DOUBLE PRECISION,
    CONSTRAINT fk_activity_zone_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_zone UNIQUE (activity_id, zone_type, zone_number),
    CONSTRAINT ck_activity_zone_type CHECK (zone_type IN ('HEART_RATE', 'POWER'))
);

-- 1:N time-ordered samples at the source's own sampling (never resampled or interpolated to 1 s).
-- Metrics without a column are kept by their source key in extra_metrics, so nothing reported is lost.
CREATE TABLE activity_sample (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id       BIGINT                   NOT NULL,
    sample_index      INTEGER                  NOT NULL,
    sample_time       TIMESTAMP WITH TIME ZONE,
    elapsed_seconds   DOUBLE PRECISION,
    distance          DOUBLE PRECISION,
    speed             DOUBLE PRECISION,
    heart_rate        DOUBLE PRECISION,
    cadence           DOUBLE PRECISION,
    power             DOUBLE PRECISION,
    elevation         DOUBLE PRECISION,
    latitude          DOUBLE PRECISION,
    longitude         DOUBLE PRECISION,
    temperature       DOUBLE PRECISION,
    extra_metrics     ${json_type},
    CONSTRAINT fk_activity_sample_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_sample UNIQUE (activity_id, sample_index),
    CONSTRAINT ck_activity_sample_index CHECK (sample_index >= 0)
);
