-- Phase 6H-1A: what happened, per activity and per detail part, the last time its detail was collected.
-- A failed or partially failed collection is recorded, never hidden behind the already-stored summary
-- activity. One row per (activity, part); each collection overwrites the row of every part it attempted.
--
--   NORMALIZED       fetched, raw stored, normalised rows written (item_count rows)
--   RAW_STORED       fetched and raw stored; this part is not normalised yet (by design)
--   EMPTY            fetched, raw stored, the source reported no data for this part
--   FETCH_FAILED     the connector/Garmin request failed; nothing stored for this part (error_code set)
--   MAPPING_FAILED   raw stored, normalisation failed; previous normalised rows untouched (error_code set)
CREATE TABLE activity_detail_collection (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id   BIGINT                   NOT NULL,
    payload_type  VARCHAR(48)              NOT NULL,
    status        VARCHAR(24)              NOT NULL,
    error_code    VARCHAR(64),
    item_count    INTEGER,
    attempted_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_detail_collection_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_detail_collection UNIQUE (activity_id, payload_type),
    CONSTRAINT ck_activity_detail_collection_status CHECK (
        status IN ('NORMALIZED', 'RAW_STORED', 'EMPTY', 'FETCH_FAILED', 'MAPPING_FAILED'))
);
