-- Phase 6H-4: derived, objective evidence about one stored activity.
--
-- This table holds measurements, never judgements. "HR rose 7.2% between halves" belongs here;
-- "endurance is poor", "the session failed", "recovery is insufficient" do not, and no column may ever
-- encode a rating, a score or a good/bad classification. Interpretation is the AI coach's job.
--
-- Everything here is re-derivable: it is computed from activity / activity_detail / activity_lap /
-- activity_zone / activity_sample plus the athlete's LTHR, and a re-analysis replaces the rows. The
-- source tables are never written by the analysis.
--
-- Every metric column is nullable. A metric the data cannot support is NULL - never zero, never an
-- estimate - and the absence of power, cadence, LTHR or interval structure is normal, not a failure.
--
--   analysis_status            can the data be analysed, not how good the session was:
--     COMPLETE          every applicable metric for this activity type was computed
--     PARTIAL           some applicable metric could not be computed from the stored data
--     INSUFFICIENT_DATA not enough stored data to compute any session metric
--   input_sample_completeness  the sample stream's fidelity at analysis time (V14), carried through so a
--                              reader can tell a full-resolution analysis from a down-sampled one; NULL
--                              when the stream was collected before fidelity was recorded.
CREATE TABLE activity_analysis (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id               BIGINT                   NOT NULL,
    analysis_version          VARCHAR(32)              NOT NULL,
    analysis_status           VARCHAR(24)              NOT NULL,
    input_sample_completeness VARCHAR(16),
    computed_at               TIMESTAMP WITH TIME ZONE NOT NULL,

    -- basis of the sample-derived metrics
    valid_sample_count        INTEGER,
    analysis_duration_seconds DOUBLE PRECISION,
    analysis_distance_meters  DOUBLE PRECISION,

    -- halves, split at the elapsed-time midpoint (never at the midpoint of the sample array)
    first_half_avg_hr         DOUBLE PRECISION,
    second_half_avg_hr        DOUBLE PRECISION,
    hr_change_bpm             DOUBLE PRECISION,
    hr_change_percent         DOUBLE PRECISION,
    first_half_avg_speed      DOUBLE PRECISION,
    second_half_avg_speed     DOUBLE PRECISION,
    speed_change_percent      DOUBLE PRECISION,
    first_half_avg_cadence    DOUBLE PRECISION,
    second_half_avg_cadence   DOUBLE PRECISION,
    cadence_change_spm        DOUBLE PRECISION,
    cadence_change_percent    DOUBLE PRECISION,

    -- speed per heartbeat, and how much it moved between halves. A RunningAI-derived descriptive
    -- metric: it is not Garmin's and not Intervals.icu's, and it carries no threshold.
    first_half_speed_hr_ratio   DOUBLE PRECISION,
    second_half_speed_hr_ratio  DOUBLE PRECISION,
    speed_hr_decoupling_percent DOUBLE PRECISION,

    -- time in heart-rate zone, straight from activity_zone; percentages are of the zone total, not of
    -- the activity duration (the two are not the same thing and the source only vouches for the former)
    hr_zone1_seconds          DOUBLE PRECISION,
    hr_zone2_seconds          DOUBLE PRECISION,
    hr_zone3_seconds          DOUBLE PRECISION,
    hr_zone4_seconds          DOUBLE PRECISION,
    hr_zone5_seconds          DOUBLE PRECISION,
    hr_zone_total_seconds     DOUBLE PRECISION,
    hr_zone1_percent          DOUBLE PRECISION,
    hr_zone2_percent          DOUBLE PRECISION,
    hr_zone3_percent          DOUBLE PRECISION,
    hr_zone4_percent          DOUBLE PRECISION,
    hr_zone5_percent          DOUBLE PRECISION,

    -- seconds at or above a share of the athlete's lactate-threshold heart rate, integrated over the
    -- real gaps between samples. NULL when no LTHR is on file: it is never substituted.
    lthr90_seconds            DOUBLE PRECISION,
    lthr95_seconds            DOUBLE PRECISION,
    lthr100_seconds           DOUBLE PRECISION,

    -- laps as the source recorded them, over every lap of the activity
    lap_count                 INTEGER,
    lap_speed_mean            DOUBLE PRECISION,
    lap_speed_stddev          DOUBLE PRECISION,
    lap_speed_cv_percent      DOUBLE PRECISION,
    lap_hr_mean               DOUBLE PRECISION,
    lap_hr_progression        DOUBLE PRECISION,
    lap_cadence_mean          DOUBLE PRECISION,

    CONSTRAINT fk_activity_analysis_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_analysis_activity UNIQUE (activity_id),
    CONSTRAINT ck_activity_analysis_status CHECK (
        analysis_status IN ('COMPLETE', 'PARTIAL', 'INSUFFICIENT_DATA')),
    CONSTRAINT ck_activity_analysis_sample_completeness CHECK (
        input_sample_completeness IS NULL OR input_sample_completeness IN ('FULL', 'DOWNSAMPLED', 'UNKNOWN'))
);

-- One row per work repetition of an identified interval group.
--
-- A group is only identified from what the device stated (intensity type + workout step index, with a
-- recovery block between occurrences). Intervals are never inferred from a speed or heart-rate pattern,
-- so an unstructured run simply has no rows here - which is an absence of structure, not a failure.
--
-- group_index numbers the identified groups in the order they start; repetition_index numbers the work
-- occurrences inside one group, from 1.
CREATE TABLE activity_analysis_interval (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_analysis_id BIGINT           NOT NULL,
    group_index          INTEGER          NOT NULL,
    repetition_index     INTEGER          NOT NULL,
    workout_step_index   INTEGER,
    first_lap_index      INTEGER,
    last_lap_index       INTEGER,
    duration_seconds     DOUBLE PRECISION,
    distance_meters      DOUBLE PRECISION,
    average_speed        DOUBLE PRECISION,
    average_hr           DOUBLE PRECISION,
    max_hr               DOUBLE PRECISION,
    average_cadence      DOUBLE PRECISION,
    average_power        DOUBLE PRECISION,
    CONSTRAINT fk_activity_analysis_interval_analysis FOREIGN KEY (activity_analysis_id)
        REFERENCES activity_analysis (id) ON DELETE CASCADE,
    CONSTRAINT uk_activity_analysis_interval UNIQUE (activity_analysis_id, group_index, repetition_index)
);

-- Repeatability of one identified group, computed over its work repetitions only: warm-up, recovery and
-- cool-down blocks are never mixed in. speed_cv_percent uses the POPULATION standard deviation (divisor
-- n, not n-1) over the repetitions present, which are the whole group rather than a sample of it.
CREATE TABLE activity_analysis_interval_group (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_analysis_id                BIGINT           NOT NULL,
    group_index                         INTEGER          NOT NULL,
    workout_step_index                  INTEGER,
    work_rep_count                      INTEGER          NOT NULL,
    mean_speed                          DOUBLE PRECISION,
    speed_stddev                        DOUBLE PRECISION,
    speed_cv_percent                    DOUBLE PRECISION,
    first_rep_speed                     DOUBLE PRECISION,
    last_rep_speed                      DOUBLE PRECISION,
    last_vs_first_speed_change_percent  DOUBLE PRECISION,
    first_rep_hr                        DOUBLE PRECISION,
    last_rep_hr                         DOUBLE PRECISION,
    hr_progression_bpm                  DOUBLE PRECISION,
    -- RunningAI interval recovery HR change: how far heart rate fell across the recovery block that
    -- follows the group's last work repetition. This is NOT Garmin's Recovery HR metric.
    recovery_start_hr                   DOUBLE PRECISION,
    recovery_end_hr                     DOUBLE PRECISION,
    recovery_hr_drop_bpm                DOUBLE PRECISION,
    recovery_duration_seconds           DOUBLE PRECISION,
    CONSTRAINT fk_analysis_interval_group_analysis FOREIGN KEY (activity_analysis_id)
        REFERENCES activity_analysis (id) ON DELETE CASCADE,
    CONSTRAINT uk_analysis_interval_group UNIQUE (activity_analysis_id, group_index)
);

CREATE INDEX idx_activity_analysis_interval_analysis ON activity_analysis_interval (activity_analysis_id);
