-- Phase 6H-5: one physical workout, several external identities. The RunningAI activity row keeps its
-- Garmin-based identity (external_source + external_id on activity, untouched); this table attaches
-- ADDITIONAL external references (today: the Intervals.icu activity id) to the same activity.
--
-- match_method records how the link was established:
--   SOURCE_ID    the Intervals payload itself names the upstream Garmin activity id
--                (live-verified 2026-10-03: source = GARMIN_CONNECT, external_id = the Garmin id)
--   EXTERNAL_ID  the payload carries the same explicit external id without naming the source
--   COMPOSITE    no explicit id; exactly one candidate matched on type + start time + duration
--                + distance within the measured tolerances (see docs/architecture/intervals-enrichment.md)
--
-- The delta columns are technical matching evidence for later debugging, not training metrics.
-- An ambiguous composite match (2+ candidates) is never linked.
CREATE TABLE activity_source_link (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id              BIGINT                   NOT NULL,
    external_source          VARCHAR(32)              NOT NULL,
    external_activity_id     VARCHAR(100)             NOT NULL,
    match_method             VARCHAR(24)              NOT NULL,
    start_time_delta_seconds INTEGER,
    duration_delta_seconds   INTEGER,
    distance_delta_meters    DOUBLE PRECISION,
    matched_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_source_link_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_source_link_external UNIQUE (external_source, external_activity_id),
    CONSTRAINT uk_activity_source_link_activity UNIQUE (activity_id, external_source),
    CONSTRAINT ck_activity_source_link_method CHECK (match_method IN ('SOURCE_ID', 'EXTERNAL_ID', 'COMPOSITE'))
);
