-- Phase 6H-5: Intervals.icu analysis enrichment, raw-first.
--
-- Terminology (live-verified 2026-10-03 against the real account):
--   CTL  = Intervals.icu's CALCULATED fitness   (activity field icu_ctl, wellness field ctl)
--   ATL  = Intervals.icu's CALCULATED fatigue   (activity field icu_atl, wellness field atl)
--   The wellness field `fatigue` is a SUBJECTIVE self-report and is NEVER mapped to ATL;
--   no ambiguous `fatigue` column exists here on purpose.
--   Form has no direct live API field; derived_form = ctl - atl is RunningAI-derived from
--   Intervals CTL/ATL (hence the column name) and only set when both inputs are present.

-- Raw Intervals.icu payloads, stored before any normalisation (same principle as activity_raw_payload):
--   ACTIVITY      one completed-activity item, external_id = the Intervals activity id (e.g. i188081596)
--   WELLNESS_DAY  one wellness entry, external_id = the ISO date that is its Intervals id
-- A re-fetch replaces payload + fetched_at in place; reprocess re-maps from here with zero API calls.
CREATE TABLE intervals_raw_payload (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id     BIGINT                   NOT NULL,
    payload_type   VARCHAR(32)              NOT NULL,
    external_id    VARCHAR(100)             NOT NULL,
    effective_date DATE,
    payload        ${json_type}             NOT NULL,
    fetched_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_intervals_raw_payload_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_intervals_raw_payload UNIQUE (athlete_id, payload_type, external_id),
    CONSTRAINT ck_intervals_raw_payload_type CHECK (payload_type IN ('ACTIVITY', 'WELLNESS_DAY'))
);

-- Per-activity Intervals.icu training-model numbers, 1:1 with the RunningAI activity. Only fields whose
-- name, type and meaning were confirmed on live responses are first-class; everything else stays in
-- intervals_raw_payload. ctl/atl_after_activity are the Intervals Fitness-chart values the activity row
-- itself carries (icu_ctl / icu_atl; live-verified equal to that day's wellness ctl/atl).
-- These values are NEVER merged into activity_analysis: different provenance, kept apart.
CREATE TABLE activity_intervals_metrics (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id           BIGINT                   NOT NULL,
    intervals_activity_id VARCHAR(100)             NOT NULL,
    training_load         INTEGER,
    intensity             DOUBLE PRECISION,
    ctl_after_activity    DOUBLE PRECISION,
    atl_after_activity    DOUBLE PRECISION,
    source_updated_at     TIMESTAMP WITH TIME ZONE,
    fetched_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_intervals_metrics_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_intervals_metrics_activity UNIQUE (activity_id)
);

-- Daily Intervals.icu fitness-model snapshot (wellness endpoint). One row per athlete-local day
-- (fitness_date = the wellness entry's own id). Missing values stay NULL, never 0. Garmin Recovery
-- remains the recovery source of truth: HRV / sleep / resting HR from wellness are kept only in the
-- raw payload and never overwrite garmin_recovery_daily.
CREATE TABLE intervals_fitness_daily (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id        BIGINT                   NOT NULL,
    fitness_date      DATE                     NOT NULL,
    ctl               DOUBLE PRECISION,
    atl               DOUBLE PRECISION,
    derived_form      DOUBLE PRECISION,
    ramp_rate         DOUBLE PRECISION,
    ctl_load          DOUBLE PRECISION,
    atl_load          DOUBLE PRECISION,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    fetched_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_intervals_fitness_daily_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_intervals_fitness_daily_athlete_date UNIQUE (athlete_id, fitness_date)
);
