-- Phase 6H-6: persistent state of the manual 90-day historical backfill. The run and its per-activity
-- checkpoints live in the database so an interrupted run (rate limit, crash, restart) resumes without
-- re-fetching what already completed. Nothing here is a scheduler: every run starts and resumes only by
-- an explicit manual API call.
--
--   status  RUNNING    currently executing in some JVM
--           PAUSED     stopped at a safe point (external failure, data-fidelity gate); manual resume allowed
--           FAILED     invariant/code failure; never auto-resumed
--           COMPLETED  all phases done and verified
--
--   current_phase is the phase the run is in (or must resume from):
--   GARMIN_DISCOVERY -> GARMIN_DETAIL_ANALYSIS -> INTERVALS_ACTIVITIES -> INTERVALS_FITNESS
--   -> GARMIN_RECOVERY -> VERIFY -> COMPLETED
--
-- next_recovery_date is the newest-first recovery cursor (the next day still to sync);
-- fitness_day_count / recovery_day_count persist progress for reporting across resumes.
-- This table never touches garmin_sync_state: the incremental-sync checkpoint is isolated by design.
CREATE TABLE historical_backfill_run (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id               BIGINT                   NOT NULL,
    start_date               DATE                     NOT NULL,
    end_date                 DATE                     NOT NULL,
    requested_days           INTEGER                  NOT NULL,
    status                   VARCHAR(16)              NOT NULL,
    current_phase            VARCHAR(32)              NOT NULL,
    stop_reason              VARCHAR(64),
    discovery_complete       BOOLEAN                  NOT NULL DEFAULT FALSE,
    target_activity_count    INTEGER,
    completed_activity_count INTEGER                  NOT NULL DEFAULT 0,
    fitness_day_count        INTEGER,
    recovery_day_count       INTEGER                  NOT NULL DEFAULT 0,
    next_recovery_date       DATE,
    started_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at             TIMESTAMP WITH TIME ZONE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_historical_backfill_run_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT ck_historical_backfill_run_status CHECK (status IN ('RUNNING', 'PAUSED', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_historical_backfill_run_phase CHECK (current_phase IN (
        'GARMIN_DISCOVERY', 'GARMIN_DETAIL_ANALYSIS', 'INTERVALS_ACTIVITIES', 'INTERVALS_FITNESS',
        'GARMIN_RECOVERY', 'VERIFY', 'COMPLETED'))
);

-- One row per Garmin activity the discovery saw inside the window (supported or not). activity_id is
-- NULL for unsupported types: those never become Activity rows. ordinal is the frozen processing order
-- (started_at ASC) assigned when discovery completes; statuses are the per-stage checkpoints that make
-- resume skip finished work. Real external ids live here because the pipeline needs them; they are not
-- echoed into logs or result documents.
CREATE TABLE historical_backfill_activity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              BIGINT                   NOT NULL,
    activity_id         BIGINT,
    garmin_external_id  VARCHAR(100)             NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    ordinal             INTEGER,
    summary_status      VARCHAR(32)              NOT NULL,
    detail_status       VARCHAR(32),
    sample_completeness VARCHAR(24),
    analysis_status     VARCHAR(32),
    intervals_status    VARCHAR(32),
    last_error_code     VARCHAR(64),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_historical_backfill_activity_run FOREIGN KEY (run_id) REFERENCES historical_backfill_run (id),
    CONSTRAINT fk_historical_backfill_activity_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_historical_backfill_activity_activity UNIQUE (run_id, activity_id),
    CONSTRAINT uk_historical_backfill_activity_external UNIQUE (run_id, garmin_external_id),
    CONSTRAINT ck_historical_backfill_activity_summary CHECK (
        summary_status IN ('CREATED', 'UPDATED', 'SKIPPED_UNSUPPORTED'))
);
