-- Athlete: the owner of activities. Single-user today, multi-athlete ready.
CREATE TABLE athlete (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    timezone    VARCHAR(64)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_athlete_name UNIQUE (name)
);
