-- Activity: normalised workout record used by RunningAI.
-- (external_source, external_id) identifies the record in the originating system
-- and is unique so repeated ingestion cannot create duplicates.
CREATE TABLE activity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id          BIGINT                   NOT NULL,
    external_source     VARCHAR(32)              NOT NULL,
    external_id         VARCHAR(100)             NOT NULL,
    activity_type       VARCHAR(32)              NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_seconds    INTEGER                  NOT NULL,
    distance_meters     DOUBLE PRECISION,
    average_heart_rate  INTEGER,
    max_heart_rate      INTEGER,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_activity_external UNIQUE (external_source, external_id)
);

-- Per-athlete timeline lookups (future filters) and the newest-first list endpoint.
CREATE INDEX ix_activity_athlete_started ON activity (athlete_id, started_at);
CREATE INDEX ix_activity_started_at ON activity (started_at);
