-- Activity raw payload: the untouched response received from an external system
-- (Garmin, Intervals.icu, ...). Kept so parsing can be re-run without re-fetching.
--
-- activity_id is NULLABLE on purpose (raw-first ingestion): the payload is stored
-- before normalisation, so a parsing failure still leaves the original data behind.
--
-- One row per external activity: a re-fetch replaces payload and fetched_at.
--
-- ${json_type} is a Flyway placeholder: JSONB on PostgreSQL, JSON on H2 (tests).
CREATE TABLE activity_raw (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id      BIGINT,
    external_source  VARCHAR(32)              NOT NULL,
    external_id      VARCHAR(100)             NOT NULL,
    payload          ${json_type}             NOT NULL,
    fetched_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_activity_raw_activity FOREIGN KEY (activity_id) REFERENCES activity (id),
    CONSTRAINT uk_activity_raw_external UNIQUE (external_source, external_id)
);
