-- Garmin incremental sync checkpoint: one row per athlete.
--
-- high_water_started_at is the newest activity start time RunningAI has
-- successfully processed from Garmin so far; last_successful_sync_at is when an
-- incremental sync last completed successfully. They differ on purpose: Garmin
-- activities can be edited after upload, so a sync always re-fetches an overlap
-- window behind the high-water mark and relies on idempotent ingestion (insert
-- vs. update) rather than a strict "since" cursor.
CREATE TABLE garmin_sync_state (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id               BIGINT                   NOT NULL,
    high_water_started_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    last_successful_sync_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_garmin_sync_state_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_garmin_sync_state_athlete UNIQUE (athlete_id)
);
