-- Athlete intensity profile: lactate-threshold heart rate (LTHR) and threshold
-- pace, the athlete data that workout intensity targets (pace / %LTHR heart
-- rate / treadmill speed) are derived from. One row per athlete; both metrics
-- are optional (a fresh athlete has neither yet) and are athlete state -- not a
-- per-workout value -- so a later update (manual edit, fitness test, future
-- Garmin LTHR detection) replaces them in place rather than versioning them.
CREATE TABLE athlete_intensity_profile (
    id                                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id                             BIGINT                   NOT NULL,
    lactate_threshold_heart_rate_bpm       INTEGER,
    lactate_threshold_pace_seconds_per_km  INTEGER,
    created_at                             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_athlete_intensity_profile_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_athlete_intensity_profile_athlete UNIQUE (athlete_id)
);
