-- AI-coach workout drafts (Phase 6E). A draft is a workout the AI coach designed and that
-- passed hard-safety validation. It is NOT an approved or published workout: this phase has no
-- approve/publish transition and nothing here ever reaches Intervals or Garmin.
--
-- Versioning instead of overwriting: revising a draft inserts a NEW row with version + 1 and
-- marks the previous row SUPERSEDED, so the sequence of what the coach proposed and how the
-- athlete's feedback changed it stays auditable. All versions of one draft share draft_group_id.
--
-- The raw AI response is deliberately not stored -- only the normalised draft, the assessment and
-- provider/model metadata. Segments are stored as JSON because they are read and written only as
-- a whole draft, are never queried field-by-field, and their shape is owned by the coach domain
-- rather than by the schema.
CREATE TABLE workout_draft (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id               BIGINT                   NOT NULL,
    draft_group_id           VARCHAR(64)              NOT NULL,
    version                  INTEGER                  NOT NULL,
    workout_date             DATE                     NOT NULL,
    status                   VARCHAR(32)              NOT NULL,
    title                    VARCHAR(200)             NOT NULL,
    workout_type             VARCHAR(64)              NOT NULL,
    total_duration_minutes   INTEGER                  NOT NULL,
    recovery_assessment      TEXT                     NOT NULL,
    load_assessment          TEXT                     NOT NULL,
    selected_workout_type    VARCHAR(64)              NOT NULL,
    rationale                TEXT                     NOT NULL,
    warnings                 ${json_type},
    segments                 ${json_type}             NOT NULL,
    provider                 VARCHAR(32)              NOT NULL,
    model                    VARCHAR(128),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_workout_draft_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_workout_draft_group_version UNIQUE (draft_group_id, version),
    CONSTRAINT ck_workout_draft_version_positive CHECK (version > 0),
    CONSTRAINT ck_workout_draft_duration_positive CHECK (total_duration_minutes > 0)
);

-- Newest draft for an athlete on a date, and the version history of one draft group.
CREATE INDEX idx_workout_draft_athlete_date ON workout_draft (athlete_id, workout_date);
CREATE INDEX idx_workout_draft_group ON workout_draft (draft_group_id, version);
