-- Daily Garmin recovery snapshot (Phase 6F): one row per athlete and athlete-local calendar day
-- (Garmin's own calendarDate). Every metric is independently nullable: a missing value means
-- Garmin had no reading for that day (no watch worn overnight, no HRV yet, ...) and is NEVER
-- replaced by a default. Values keep Garmin's units: HRV in milliseconds, sleep in seconds, resting
-- heart rate in bpm, Body Battery and stress on Garmin's 0-100 scales. hrv_status is Garmin's own
-- label (e.g. BALANCED), stored verbatim; RunningAI adds no rating of its own.
--
-- Re-syncing a day is idempotent: the row is updated in place (unique athlete_id + recovery_date),
-- and a metric Garmin did not return this time never clears a value stored earlier.
CREATE TABLE garmin_recovery_daily (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id                BIGINT                   NOT NULL,
    recovery_date             DATE                     NOT NULL,
    hrv_last_night_avg_ms     DOUBLE PRECISION,
    hrv_weekly_avg_ms         DOUBLE PRECISION,
    hrv_status                VARCHAR(32),
    sleep_duration_seconds    INTEGER,
    sleep_score               INTEGER,
    resting_heart_rate_bpm    INTEGER,
    body_battery_highest      INTEGER,
    body_battery_lowest       INTEGER,
    body_battery_charged      INTEGER,
    body_battery_drained      INTEGER,
    stress_average            INTEGER,
    stress_max                INTEGER,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_garmin_recovery_daily_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_garmin_recovery_daily_athlete_date UNIQUE (athlete_id, recovery_date),
    CONSTRAINT ck_garmin_recovery_daily_hrv CHECK (hrv_last_night_avg_ms IS NULL OR hrv_last_night_avg_ms >= 0),
    CONSTRAINT ck_garmin_recovery_daily_hrv_weekly CHECK (hrv_weekly_avg_ms IS NULL OR hrv_weekly_avg_ms >= 0),
    CONSTRAINT ck_garmin_recovery_daily_sleep CHECK (sleep_duration_seconds IS NULL OR sleep_duration_seconds >= 0),
    CONSTRAINT ck_garmin_recovery_daily_sleep_score CHECK (sleep_score IS NULL OR sleep_score >= 0),
    CONSTRAINT ck_garmin_recovery_daily_rhr CHECK (resting_heart_rate_bpm IS NULL OR resting_heart_rate_bpm > 0),
    CONSTRAINT ck_garmin_recovery_daily_bb CHECK (
        (body_battery_highest IS NULL OR body_battery_highest >= 0) AND
        (body_battery_lowest IS NULL OR body_battery_lowest >= 0) AND
        (body_battery_charged IS NULL OR body_battery_charged >= 0) AND
        (body_battery_drained IS NULL OR body_battery_drained >= 0)),
    CONSTRAINT ck_garmin_recovery_daily_stress CHECK (
        (stress_average IS NULL OR stress_average >= 0) AND (stress_max IS NULL OR stress_max >= 0))
);
