-- Phase 6G: explicit athlete approval of an AI-coach workout draft. One row per approval, written in the same
-- transaction that moves workout_draft.status DRAFT -> APPROVED, so the approval is auditable on its own and the
-- database itself refuses the two states the publish path must never see:
--   * the same draft approved twice                        (uk_workout_draft_approval_draft)
--   * two different drafts approved for one athlete + date (uk_workout_draft_approval_athlete_date)
-- The second matters because the Intervals.icu event identity is per athlete and date: publishing two approved
-- drafts for one date would let the second silently UPDATE the first.
--
-- Approval is a lifecycle fact only. It never publishes anything; the external publish outcome lives in
-- workout_draft_publication (V10).
CREATE TABLE workout_draft_approval (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id      BIGINT                   NOT NULL,
    athlete_id    BIGINT                   NOT NULL,
    workout_date  DATE                     NOT NULL,
    approved_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_workout_draft_approval_draft FOREIGN KEY (draft_id) REFERENCES workout_draft (id),
    CONSTRAINT fk_workout_draft_approval_athlete FOREIGN KEY (athlete_id) REFERENCES athlete (id),
    CONSTRAINT uk_workout_draft_approval_draft UNIQUE (draft_id),
    CONSTRAINT uk_workout_draft_approval_athlete_date UNIQUE (athlete_id, workout_date)
);
